_templates: 
  - &ecr-auth
    ecr#v2.1.0:
      login: true
      account_ids: "896069866492"
      no-include-email: true
      region: "eu-west-1"

steps:

  - label: ":docker: Build"
    plugins:
      - *ecr-auth
    command: |
      make publish

  - block: ":rocket: Deploy to production! :dragon:"
    fields:
      - select: "I'm sure, I'm deploying to PRODUCTION!"
        key: "unleash-the-dragon"
        options:
          - label: ":dragon_face: yes, unleash the dragon! :dragon:"
            value: "yes"

  - label: ":docker: Tag Image"
    plugins:
      - *ecr-auth
    command: |
      make tag-prod-image

  - wait

  - label: ":helm: :arrow_right: :k8s: production"
    command: |
      make deploy
    plugins:
      - *ecr-auth
      - ssh://git@github.com/reevoo/konfiguration-buildkite-plugin.git#v0.0.2: ~
      - ssh://git@github.com/reevoo/git-buildkite-plugin.git#v0.0.3:
          repo: git@github.com:reevoo/charts.git
          branch: v4.0
          dest: charts
      - docker#v2.0.0:
          image: "896069866492.dkr.ecr.eu-west-1.amazonaws.com/kube-release:eks-helm3"
          workdir: "/app"
          volumes:
            - ".:/app"
          environment:
            - "K8S_CLUSTER"
            - "K8S_NAMESPACE"
            - "BUILDKITE_COMMIT"
    env:
      K8S_CLUSTER: zeus
      K8S_NAMESPACE: production
